// Single source of truth for all navigation route names
export const ROUTES = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  PHONE_LOGIN: 'PhoneLogin',
  HOME: 'Home',
  FRIENDS: 'Friends',
  SEARCH_USERS: 'SearchUsers',
  WHERE_TO_GO: 'WhereToGo',
  WHAT_HAPPENING: 'WhatHappening',
  SPUR_OF_MOMENT: 'SpurOfMoment',
  CREATE_SPUR: 'CreateSpur',
  PROFILE_SETTINGS: 'ProfileSettings',
  OPEN_CHAT: 'OpenChat',
  CREATE_OPEN_CHAT: 'CreateOpenChat',
  HAPPENING_FEED: 'HappeningFeed',
  CREATE_HAPPENING: 'CreateHappening',
  MEMBER_PROFILE: 'MemberProfile',
  MESSAGES: 'Messages',
  CHAT: 'Chat',
  NOTIFICATIONS: 'Notifications',
  NIGHT_OUT: 'NightOut',
  CREATE_NIGHT_OUT: 'CreateNightOut',
  NIGHT_OUT_DETAIL: 'NightOutDetail',
  CLUB_GROUPS: 'ClubGroups',
  CLUB_DETAIL: 'ClubDetail',
  CREATE_CLUB: 'CreateClub',
  AT_VENUE: 'AtVenue',
  VENUE_HUB: 'VenueHub',
  VENUE_SEARCH: 'VenueSearch',
  VENUE_REVIEWS: 'VenueReviews',
  MEMBERS_AT: 'MembersAt',
  TRENDING_VENUES: 'TrendingVenues',
  TOP_VENUES: 'TopVenues',
  COMPLETE_PROFILE: 'CompleteProfile',
};
